name = "SmoothNumbers"
uuid = "48ae9875-8a8b-401f-9c90-1ad5d6adef54"
authors = ["Federico Stra <stra.federico@gmail.com> and contributors"]
version = "0.1.0-DEV"

[deps]
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"

[compat]
julia = "1.6"
Primes = "0.5"
